package constants

const (
	FLUENTD_IP_PORT = "FLUENTD_IP_PORT"
	PORT            = "PORT"
	EUREKA_SERVER   = "EUREKA_SERVER"
	APP_IP_PORT     = "APP_IP_PORT"
	HTTPS_ENABLE    = "HTTPS_ENABLE"
	HTTPS_CERT      = "HTTPS_CERT"
	HTTPS_KEY       = "HTTPS_KEY"
	HTTP_AUTH_TOKEN = "HTTP_AUTH_TOKEN"
)
